package randimgen;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;


public class create_File {

    public static class genConf {
        Random randomConf = new Random();

        public boolean isRandomNoise = randomConf.nextBoolean();
        public boolean isBigLines = randomConf.nextBoolean();
        public boolean isMediumLines = randomConf.nextBoolean();
        public boolean isSmallLines = randomConf.nextBoolean();
        public boolean isCheckerboard = randomConf.nextBoolean();
        public boolean isReverseCheckOrDiag = randomConf.nextBoolean();
        public boolean isRandomDiag = randomConf.nextBoolean();
    }


    public static void getOutDataToFile(boolean stringToPic) throws IOException {
        // FILE CONFIG
        File makeFile = new File("randimg.bmp");
        
        int x_total = 1280;
        int y_total = 720;
        //
        // INITIALIZE AN EMPTY BYTEARRAY STREAM
        ByteArrayOutputStream outputData = new ByteArrayOutputStream();

        byte[] hardcoded_header = getHeader();
        outputData.write(hardcoded_header);

        // OUTDATETOFILE CONTAINS THE PIXEL DATA, GENERATED BY THE MAKEPIXELDATA METHOD
        byte[] outDataToFile = makePixelData(y_total, x_total, outputData,stringToPic);

        // GENERATES THE FILE
        write_File(outDataToFile, makeFile);

        // Get index
        //int ind_y = 0;
        //int ind_x = 0;

        // HEIGHT OF THE WANTED INDEX * TOTAL WIDTH = IT REACHES THE NECESSARY HEIGHT
        // LINE 3 == 3 * 1280 IT GOES 3 TIMES THROUGH 1280 PIXELS // 3 TIMES THE FULL WIDTH OF THE PICTURE
        // IT ADDS INDEX X TO REACH THE SELECTED WIDTH == (3)[Y-> DESIRED INDEX] * 1280[FULL WIDTH SIZE] + 5[X DESIRED INDEX, PIXEL 5]
        // NEEDS TO BE MULTIPLIED BY 3 BECAUSE THE PIXELS HAVE 3 BYTES = B G R
        //
        // FULL FORMULA
        //
        // (index_y * x_total + index_x) * 3 = DESIRED INDEX
        //
        //int index = (ind_y * x_total + ind_x) *3;        
    }

    private static byte[] makePixelData(int y_total, int x_total, ByteArrayOutputStream outputData, boolean writeString) throws IOException{


        int[] integerUserString = new int[0];

        genConf configurationB = new genConf();
        //configurationB.isCheckerboard = true;

        genConf configurationG = new genConf();
        //configurationG.isReverseCheckOrDiag = true;
        
        genConf configurationR = new genConf();
        //configurationR.isRandomDiag = true;

        int blue = 0;
        int green = 0;
        int red = 0;

        if(writeString){
            integerUserString = convertStringToInt(stringGetter());
        }

        // PIXEL DATA
        // VERTICAL


        for(int y = 0; y < y_total; y++){
            ByteArrayOutputStream row = new ByteArrayOutputStream();

            //HORIZONTAL
            for(int x = 0 ; x < x_total ; x++){
                if(writeString && y == 0){
                    // HEAD AND TAIL USES 137 TO SYMBOLIZE
                    // HEAD OF TEXT FROM 0 TO 16
                    Random r = new Random();

                    if(x < 2){
                        blue = 64;
                        red = r.nextInt(65,122);
                        green = r.nextInt(65,122);
                        System.out.println("INSERTING HEADER");
                    }
                    else if((x - 2) < integerUserString.length){
                        blue = integerUserString[x-2];
                        red = r.nextInt(65,122);
                        green = r.nextInt(65,122);
                        System.out.println("INSERTING USERSTRING");
                    }
                    // TAIL OF TEXT FROM LAST CHAR TO 32
                    else if(((x - 2) - integerUserString.length) < 2){
                        blue=21;
                        red = r.nextInt(65,122);
                        green = r.nextInt(65,122);
                        System.out.println("INSERTING TAIL");
                    }
                }
                else{
                    blue = set_color(blue, x, y, x_total, y_total, configurationB);
                    green = set_color(green, x, y, x_total, y_total, configurationG);
                    red = set_color(red, x, y, x_total, y_total, configurationR);
                }

                row.write(blue);
                row.write(green);
                row.write(red);
            }

            // ADD THE DATA
            outputData.write(row.toByteArray());
        }

        return outputData.toByteArray();
    }

    static String readFile(File fileToRead) throws IOException{
        Path filepath = Paths.get(fileToRead.toURI());

        byte[] byteArray = Files.readAllBytes(filepath);
        byte[] header = getHeader();
        StringBuilder userString = new StringBuilder();

        int headcount = 0;

        for(int i = header.length; i < byteArray.length; i++){
            if(i % 3 == 0){
                int byteToInteger = byteArray[i] & 0xFF;
                char character = (char) byteToInteger;

                if(character == '@' && headcount < 2){
                    headcount++;
                }

                if(headcount == 2){
                    System.out.println("[LETTER]" + character + " [INTEG] " + byteToInteger + " [ I ] " + i);
                    if(byteToInteger == 21){
                        break;
                    } else {
                        userString.append(character);

                    }
                }
            }
        }
        System.out.println(userString);
        return userString.toString();
    }

    private static void write_File(byte[] outDataToFile, File makeFile) throws IOException{
        // WRITING
        try(FileOutputStream outputStream = new FileOutputStream(makeFile)){
            outputStream.write(outDataToFile);
        }
    }

    private static int set_color(int color, int x, int y ,  int x_total, int y_total, genConf configuration){
        int color_limit = 255;

        Random random = new Random();

        int randomC = random.nextInt(0,color_limit);
        int randomX = random.nextInt(0,x_total);
        int randomY = random.nextInt(0,y_total);

        if(configuration.isRandomNoise){
            return randomC;
        }

        else if(configuration.isBigLines){
            if(x == randomX){
                color = 0;
            }
            if(x > (x_total / 2)){
                color += 1;
            }
        }
        else if(configuration.isMediumLines){
            if(x == randomX){
                color = 255;
            }
            if(x > (x_total / 2)){
                color -= 1;
            }
        }

        else if(configuration.isSmallLines){
            if(y == randomY){
                color = 255;
            }
            else{
                color -= 1;
            }
        }

        else if(configuration.isCheckerboard || configuration.isReverseCheckOrDiag || configuration.isRandomDiag){
            int result = 0;
            int size = 20;

            if(configuration.isReverseCheckOrDiag){
                result = 1;
            }
            if(configuration.isRandomDiag){
                size = random.nextInt(1,128);
            }

            if( (x / size + y / size) % 2 == result ){
                color = 255;
            }
            else{
                color = 0;
            }
        }


        return Math.clamp(color, 0, color_limit);
    }

    public static int[] convertStringToInt(String text) {

        int[] userString_int = new int[text.length()];

        for (int i = 0; i < text.length(); i++) {
            int charsToInt = text.charAt(i);
            userString_int[i] = charsToInt;
        }

        return userString_int;
    }

    public static String stringGetter(){
        return make_Window.getterString();
    }

    private static byte[] getHeader(){
        // HEADER
        // TO CHANGE RESOLUTION SEARCH FOR COMMENTED BYTES
        // THE BYTES CHANGED NEED TO BE IN LITTLE ENDIAN
        return new byte[]{
            // FILE HEADER
            (byte) 0x42, // B
            (byte) 0x4D, // M

            (byte) 0x36,
            (byte) 0x30,
            (byte) 0x2A,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x36,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x28,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,

            // WIDTH = 1280 = 0x00000500
            (byte) 0x00, // W == 1280 = Little Endian == 0x500
            (byte) 0x05,
            (byte) 0x00,
            (byte) 0x00,

            // HEIGHT = 720 = 0x000002D0
            (byte) 0xD0, // Y == 720 = Little Endian == 0x2D0
            (byte) 0x02,
            (byte) 0x00,
            (byte) 0x00,

            (byte) 0x01,
            (byte) 0x00,
            (byte) 0x18,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x30,
            (byte) 0x2A,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00
    };
    }
}
