package randimgen;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Random;


public class create_File {

    public static class genConf {
        Random randomConf = new Random();

        public boolean isRandomNoise = randomConf.nextBoolean();
        public boolean isBigLines = randomConf.nextBoolean();
        public boolean isMediumLines = randomConf.nextBoolean();
        public boolean isSmallLines = randomConf.nextBoolean();
        public boolean isCheckerboard = randomConf.nextBoolean();
        public boolean isReverseCheckOrDiag = randomConf.nextBoolean();
        public boolean isRandomDiag = randomConf.nextBoolean();
    }


    public static void getOutDataToFile(boolean stringToPic) throws IOException {
        // FILE CONFIG
        File makeFile = new File("randimg.bmp");
        
        int x_total = 1280;
        int y_total = 720;
        //
        // INITIALIZE AN EMPTY BYTEARRAY STREAM
        ByteArrayOutputStream outputData = new ByteArrayOutputStream();

        byte[] hardcoded_header = getHeader();
        outputData.write(hardcoded_header);


        // OUTDATETOFILE CONTAINS THE PIXEL DATA, GENERATED BY THE MAKEPIXELDATA METHOD
        byte[] outDataToFile = makePixelData(y_total, x_total, outputData,stringToPic);

        // GENERATES THE FILE
        write_File(outDataToFile, makeFile);

        // Get index
        //int ind_y = 0;
        //int ind_x = 0;

        // HEIGHT OF THE WANTED INDEX * TOTAL WIDTH / IT REACHES THE NECESSARY HEIGHT
        // LINE 3 == 3 * 1280 IT GOES 3 TIMES THROUGH 1280 PIXELS OR THE FULL WIDTH OF THE PICTURE 
        // IT ADDS INDEX X TO REACH THE SELECTED WIDTH == 3 * 1280 + 5 IF PIXEL 5
        // MULTIPLIED BY 3 BECAUSE THE PIXELS HAVE 3 BYTES = B G R

        //int index = (ind_y * x_total + ind_x) *3;        
    }

    private static byte[] makePixelData(int y_total, int x_total, ByteArrayOutputStream outputData, boolean writeString) throws IOException{
        
        Random randomConf = new Random();

        int[] integerUserString = new int[0];

        genConf configurationB = new genConf();
        //configurationB.isCheckerboard = true;

        genConf configurationG = new genConf();
        //configurationG.isReverseCheckOrDiag = true;
        
        genConf configurationR = new genConf();
        //configurationR.isRandomDiag = true;

        int blue = 0;
        int green = 0;
        int red = 0;

        if(writeString){
            integerUserString = convertStringToInt(stringGetter());
        }

        // PIXEL DATA
        // VERTICAL
        for(int y = 0; y < y_total; y++){
            ByteArrayOutputStream row = new ByteArrayOutputStream();

            //HORIZONTAL
            for(int x = 0 ; x < x_total ; x++){
                if(writeString && y == 1){
                    // HEAD AND TAIL USES 137 TO SYMBOLIZE
                    // HEAD OF TEXT FROM 0 TO 16
                    if(x < 16){
                        blue = 137;
                    }
                    if((x - 16) < integerUserString.length){
                        blue = integerUserString[x - 16];
                    }
                    // TAIL OF TEXT FROM LAST CHAR TO 32
                    else if((x - 16) > ((x - 16) + integerUserString.length) && !((x - 16 - integerUserString.length) > 32)){
                        blue = 137;
                    }
                }

                blue = set_color(blue, x, y, x_total, y_total, configurationB);;
                green = set_color(green, x, y, x_total, y_total, configurationG);
                red = set_color(red, x, y, x_total, y_total, configurationR);

                row.write(blue);
                row.write(green);
                row.write(red);
            }

            // ADD THE DATA
            outputData.write(row.toByteArray());
        }

        return outputData.toByteArray();
    }

    private static void read() throws IOException{

        Path filepath = Paths.get("randimg.bmp");
        // READING
        byte[] byteArray = Files.readAllBytes(filepath);


        // READING


        // THE HEADER ENDS AT BYTE 138
        // EXTRACTED FROM INTERNET
        for(int i = 0; i < Math.min(50000, byteArray.length); i++){
             System.out.printf("         0x%02X%s%n",
                byteArray[i] & 0xFF,
                i < 137 ? "," : "");
                if (i % 16 == 0) {
                    System.out.printf("%n%04X: ", i);
                }
                System.out.printf("%02X ", byteArray[i] & 0xFF);
    
    }
    }

    private static void write_File(byte[] outDataToFile, File makeFile) throws IOException{
        // WRITING
        try(FileOutputStream outputStream = new FileOutputStream(makeFile)){
            outputStream.write(outDataToFile);
        }
    }

    private static int set_color(int color, int x, int y ,  int x_total, int y_total, genConf configuration){
        int color_limit = 255;

        Random random = new Random();

        int randomC = random.nextInt(0,color_limit);
        int randomX = random.nextInt(0,x_total);
        int randomY = random.nextInt(0,y_total);


        if(configuration.isRandomNoise){
            return randomC;
        }

        else if(configuration.isBigLines){
            if(x == randomX){
                color = 0;
            }
            if(x > (x_total / 2)){
                color += 1;
            }
        }
        else if(configuration.isMediumLines){
            if(x == randomX){
                color = 255;
            }
            if(x > (x_total / 2)){
                color -= 1;
            }
        }

        else if(configuration.isSmallLines){

            if(y == randomY){
                color = 255;
            }
            else{
                color -= 1;
            }
        }

        else if(configuration.isCheckerboard || configuration.isReverseCheckOrDiag || configuration.isRandomDiag){
            int result = 0;
            int size = 20;

            if(configuration.isReverseCheckOrDiag){
                result = 1;
            }
            if(configuration.isRandomDiag){
                size = random.nextInt(1,128);
            }

            if( (x / size + y / size) % 2 == result ){
                color = 255;
            }
            else{
                color = 0;
            }
        }


        return Math.clamp(color, 0, color_limit);
    }

    public static int[] convertStringToInt(String text){

        int[] userString_int = new int[text.length()];

        for(int i = 0; i < text.length(); i++){
            int charsToInt = (int) text.charAt(i);
            userString_int[i] = charsToInt;
        }

        System.out.println(Arrays.toString(userString_int));
        return userString_int;

    }

    public static String stringGetter(){
        return make_Window.getterString();
    }

    private static byte[] getHeader(){
        // HEADER
        // TO CHANGE RESOLUTION SEARCH FOR COMMENTED BYTES
        // THE BYTES CHANGED NEED TO BE IN LITTLE ENDIAN

        return new byte[]{
            // FILE HEADER
            (byte) 0x42, // B
            (byte) 0x4D, // M

            (byte) 0x36,
            (byte) 0x30,
            (byte) 0x2A,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x36,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x28,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,

            // WIDTH = 1280 = 0x00000500
            (byte) 0x00, // W == 1280 = Little Endian == 0x500
            (byte) 0x05,
            (byte) 0x00,
            (byte) 0x00,

            // HEIGHT = 720 = 0x000002D0
            (byte) 0xD0, // Y == 720 = Little Endian == 0x2D0
            (byte) 0x02,
            (byte) 0x00,
            (byte) 0x00,


            (byte) 0x01,
            (byte) 0x00,
            (byte) 0x18,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x30,
            (byte) 0x2A,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x00
    };
    }
}
